### ISSUE TITLE
Ask people in Huxley for help to de-spaghetti the code

### ISSUE THREAD

**Issue by cbeuw** [mrc-ide/covid-sim#163]
Do this before tech companies find out

Otherwise us Computing students won't be able to get jobs and internships

Please

**Comment by weshinsley** [comment]
Microsoft and Github are involved in refactoring the code, so I do not think you need to worry about the tech companies, nor that the make-up of this code will reflect badly on Imperial. Follow John Carmack's twitter feed, partly as he worked on the code and did not share your concerns, and partly because you should know who he is and follow his twitter feed. 

The code will take some time to understand, but there are those who have done so and are interacting with us to discuss it.

**Comment by MrHash** [comment]
When you say Github presumably you meant Microsoft.

**Comment by MrHash** [comment]
Github was acquired by Microsoft, perhaps you don't know this.

**Comment by weshinsley** [comment]
Of course, but that does not make them the same thing. The teams worked on different things from different places and had clearly separate identities, providing different kinds of support to us, and to each other.
