### ISSUE TITLE
Variable shadowing (j) in DoCase 

### ISSUE THREAD

**Issue by pulkin** [mrc-ide/covid-sim#169]
Disclaimer: I am in no way related to PVS Studio and their developers who kindly allowed checking arbitrary projects without buying their software.

Somebody dumped issue #165 into our work chat. I've run PVS studio (static analyser) on this repo just to make my own judgement on how bad (or good) the code quality is. Unfortunately, I did not build up any opinion on that regard but you guys might be interested in fixing these two `error`-level entries. Line numbers are offset by 2 or 3.

```bash
SetupModel.cpp	1058	err	V781 The value of the 'm' index is checked after it was used. Perhaps there is a mistake in program logic.
Update.cpp	799	err	V535 The variable 'j' is being used for this loop and for the outer loop. Check lines: 789, 799.
```

Besides these two, I think there is a massive potential for random memory corruption through `fscanf`, `sscanf` and `sprintf`, example (around 70 spotted throughout the code):

```bash
CovidSim.cpp  2421    warn    V512 A call of the 'sprintf' function will lead to overflow of the buffer 'outname'.
```

Please use `*nprintf`.

**Comment by igfoo** [comment]
Thanks for the reports. It looks like
```
SetupModel.cpp	1058	err	V781 The value of the 'm' index is checked after it was used. Perhaps there is a mistake in program logic.
```
refers to
```
            denom_household[m]++;
            for (i2 = 0; i2 < m; i2++)
```

This doesn't look like a bug to me. First we record that there is a household of size `m`, and then we use `i2` to index each of the people in that household.

**Comment by pulkin** [comment]
It is this line:

```c
while ((s > P.HouseholdSizeDistrib[ad][m - 1]) && (k + m < Mcells[j].n) && (m < MAX_HOUSEHOLD_SIZE)) m++;
```

I think the logic assumed by the analyser is that the condition `m < MAX_HOUSEHOLD_SIZE` checks the size of `P.HouseholdSizeDistrib[ad]`.

**Comment by igfoo** [comment]
Ah, OK. Still looks like that one is a false positive, then.

The other one does look worth looking into though, with the loops https://github.com/mrc-ide/covid-sim/blob/60da1ecff99001758499292b4751e4fdbb92cfd2/src/Update.cpp#L786 and https://github.com/mrc-ide/covid-sim/blob/60da1ecff99001758499292b4751e4fdbb92cfd2/src/Update.cpp#L796 using the same variable. The tests still pass if I make the inner one use a fresh variable, which I think is because [people only belong to one place](https://github.com/mrc-ide/covid-sim/blob/60da1ecff99001758499292b4751e4fdbb92cfd2/src/SetupModel.cpp#L1849), so the `a->PlaceLinks[j] >= 0` conditional of the outer loop is only true for one value of `j` anyway.

But in order to be robust against future changes, I think the inner loop should be changed. However, I'm not sure whether the right fix is to use a fresh loop variable, or to only call `DoPlaceClose` for the current `j` value.

Perhaps you could take a look at this please, @weshinsley?

**Comment by weshinsley** [comment]
OK - I've had a chat about this and it's in some functionality to do with a special kind of work-place absenteeism, which is not switched on for any covid runs. Is PVS detecting this with a static analysis? Intel Inspector hasn't picked anything up running live. (I still am a bit surprised I'm not seeing it in my VS warnings, but anyway...)

We should fix it anyway.

The two shadows (for int j) are clear in terms of scope, just not good form, so we should carefully rename those and all j-refs within...

The reuse of j on 796 one I'm thinking I should check with Neil when he's free. People indeed belong to only one place type, which is possibly significant. If we renamed j on 796, we should then break the outer-j loop when we finish with the inner one - since that's what would have happened before, and that might make sense, again, because of the one place membership. I need to get my head around what the two nested j-loops do. (Potentially, it might be a kind of "optimised loop exit" that wasn't so unusual 15 years back, but looks pretty hideous now)

But for now I think no panic, as I don't think this code is entered in current runs.

**Comment by pulkin** [comment]
Yes, it is a static analyser, sorry for not mentioning it. It is guided by the output of your `cmake`.

**Comment by weshinsley** [comment]
No worries - just glad that's the case and that we're right in thinking it's not live with the covid urrent model params. (Yes, many things in the past were thought to optimise things but probably did not...!)

**Comment by weshinsley** [comment]
Think this is all sorted out with that merge. Thanks all
