### ISSUE TITLE
Copyright note conflicts with Copyleft license

### ISSUE THREAD

**Issue by tauoverpi** [mrc-ide/covid-sim#180]
The copyright notice at the top of the file conflicts with the copyleft license of the project as it explicitly states one may not distribute nor copy without permission while GPL requires the ability to copy, modify, and distribute.

https://github.com/mrc-ide/covid-sim/blob/60da1ecff99001758499292b4751e4fdbb92cfd2/src/CovidSim.cpp#L1-L4

**Comment by MattWoodhead** [comment]
No it doesnt.

It is a [requirement of the GPL license](https://www.gnu.org/licenses/gpl-howto.html).

The copyright notice allows the open source license to be enforced.

**Comment by GalaxyAllie** [comment]
I noticed this too, due to the wording of it. While a copyright notice is needed (somewhere, not necessarily in a source code comment at the top) to enforce GPL, I do think the wording of this one may be unclear to people new to the GPL.

The [reference GPL copyright notice](https://www.gnu.org/licenses/gpl-3.0.html#howto) might be a good place to start with wording that's possibly a bit more clear (and has been reviewed by the Free Software Foundation and their lawyers, because I am definitely not a lawyer)?

**Comment by weshinsley** [comment]
Thanks for flagging this - we had a PR for this already that had stalled before merging. Opinion was that it was superceded by the license, which was more clear.
