### ISSUE TITLE
[Medium]Investigate the High memory footprint issue

### ISSUE THREAD

**Issue by Feynstein** [mrc-ide/covid-sim#192]
There might exist ways to make it less memory heavy... there might be a problem with stack memory leak... I don't know, but it might be a cause. Because of a loop with a leak that runs for too long for example.

**Comment by matt-gretton-dann** [comment]
Thank you for raising this issue.

High-memory usage is expected as there are large arrays of large data structures initialised for the model.  Which isn't to say that it can't be improved.

The low-hanging fruit is to go through and make every type sized (`int32` instead of `int` etc).  At the moment various uses of `long` make Linux memory usage higher than Windows (`long` on Linux is 64-bit, vs 32-bit on Windows).  This would require careful review.

Next: some flags/small values are stored as ints.  They could be reduced to bit-fields or chars.

Finally, and the hardest, would be to change the underlying data types.  With some data changes various `double` types could be stored as `int32` - reducing footprint and hopefully speeding up the code.  But this would require careful planning and review.

**Comment by Feynstein** [comment]
My pleasure :-) I will try to see what I can do with data reduction in my fork. I still don't know all the intrications of it yet, but when I deal with huge amount of images, I try to use right-in-time loading and unloading. It affects performance only if it's in repeated parts of the code. Many a times did I went for lunch in my first days only to come back with my computer running on fumes in the swap... So I'll try to do it in my fork if I can.

**Comment by Feynstein** [comment]
I was also thinking of looking for ways to represent the data with a lossless kind of interpolation. I know there is geographic data in it, I will look into it but I think that nurbs might be a good way.

**Comment by hipparchus2000** [comment]
You could consider creating a pool structure to reuse memory chunks of a given size rather than continuously malloc/free. Having worked in realtime embedded c++, this was a useful technique for performance improvement. Otherwise you are relying on the system garbage collector. But even if you called the gc occasionally it would be comparatively slow and you'd still have heap fragmentation especially with multiple threads which may be allocating objects of different sizes at different times. Obviously suggest pool methods made thread safe with mutexes.

**Comment by hipparchus2000** [comment]
Also note bit stuffing and int32 from long will probably make slower code. I come from long ago so I tried this to beat performance of real time c++ compilers but failed. The reason is obvious. Data paths are typically 64 bits wide (wider still if cache lines). If you add two 64 bit values in a 64 bit Alu, in a risc, which x86 more of less is, or arm64, this takes 1 cycle. If you add two 8, 16, or 32 bit values, you have to mask the inputs and output with and operations. You see this by generating assembler from the c++.

**Comment by weshinsley** [comment]
Gradual cleaning up of old issues... the high memory footprint is expected and consistent with the volume of data for individuals and contact matrices. We do the memory acquisition once at the beginning, so there's no continuous new/free, and no gc during the main code. Bit packing in earlier days was for space needs when machines were smaller; the rest I guess we are letting the compiler optimise for now as it sees fit. But I don't think there's a lot to gain right now from memory analysis.
