### ISSUE TITLE
Decompose into pure functions and eliminate mutable globals.

### ISSUE THREAD

**Issue by robscovell-ts** [mrc-ide/covid-sim#271]
It is possible that the determinacy issues such as #116 are caused by lack of thread safety when running the model on multiple cores. This could be mitigated by decomposing the model into pure functions, and then recomposing the model from those functions. Mutable globals must also be eliminated. This would obviously require a huge amount of refactoring but the benefit would be that each function can be verified as fit for purpose and validated through full-coverage testing.

**Comment by weshinsley** [comment]
See pinned issue #161 - the codebase is fully thread safe, with one well discussed safe but non-deterministic region in the initialisation, so these sorts of refactors may be helpful in clearing up the code and allowing easier testing, but are irrelevant to determinism/threading (I will rename the issue to avoid yet more confusion on that point)

Best thing for now is to try and make concise PRs that fix a piece at a time, rather than the huge refactors, which we won't be able to do much with while the code is in live emergency use.

**Comment by robscovell-ts** [comment]
Thank you @weshinsley . You are right in issue #161  in your comment about stastically equivalent run results not being a problem. It is probably the key point to be made clearly in the discussion around determinism and thread-predictability because previous comments made about it have led to misunderstandings in online discussions about the model.

**Comment by seanmorris** [comment]
If the simulation shows [demons flying out of people's noses](http://catb.org/jargon/html/N/nasal-demons.html) will that mean we'll need more masks?

**Comment by robscovell-ts** [comment]
@seanmorris Ahhh Usenet. That takes me back!

**Comment by robscovell-ts** [comment]
@seanmorris  Do mutant globals mean we've got an even worse apocalypse on our hands?
