### ISSUE TITLE
Algorithm to map a point to a microcell

### ISSUE THREAD

**Issue by galactic-src** [mrc-ide/covid-sim#338]
To allocate the population, it maps population densities to microcells and aggregates all density points falling into a given microcell, then uses a binomial distribution sampling procedure to allocate individuals.

Code: https://github.com/mrc-ide/covid-sim/blob/dfc6402db34c174e41d9afcba3b4f49d7ff1f425/src/SetupModel.cpp#L779

Density data have a floating point x/y coordinate and to map to a microcell, it translates according to our SpatialBoundingBox, then divides by the width of 1 microcell, returning the fraction of the way along the bounding box; so far so good.

However, we then add 0.1 before calling floor() then multiplying by the number of microcells. I'm scratching my head as to why 0.1 is the right number to add here - any ideas?

Consider a simple grid: 
- area 10 microcells wide,
- microcell edge length 0.1,
- SpatialBoundingBox axis from 0.0 - 1.0 (no translation required).

We have an entry at 0.09 to allocate
- we subtract the lower bound, 0.0 (nothing to do)
- we divide by 0.1, giving 0.9
- we add 0.1, giving 1.0, then take floor() and convert to an int - this is the lowest value that resolves to index 1

So I think that values [0-0.9) end up in bucket 0 and values (8.9-10.0) end up in bucket 9.

Any ideas of the reason for adding 0.1? Does it guard against certain data, or correct for some adjustment of bounds elsewhere?

**Comment by weshinsley** [comment]
Without looking in great detail, I suspect floor(x+0.1) is likely to be an early form of round(x), to handle where x might be fractionally below the "intended" integer due to precision issues. This code was originally ANSI compliant, in an era long ago where that was a useful/necessary thing to be (for running on super-computers probably). ANSI C didn't have round() - had to wait patiently until C99 for that... so (int) float(x + any number more than about 1e-6 and strictly less than 0.5) I used to see quite often in that generation of code, to prevent an (int)x cast returning x-1.

The floating point numbers will be related to the 1/120 degree lon/lat resolution of the spatial population data - in the text-based population input files this represents the lower-left corner (Southern, Western) of a cell of size (1/120, 1/120) degrees - hence raster grid is 43200x21600 in the end.
