### ISSUE TITLE
Recent commit requires recreating network files on linux

### ISSUE THREAD

**Issue by krishnakumarg1984** [mrc-ide/covid-sim#347]
Commit [0300a2f63efd47](https://github.com/mrc-ide/covid-sim/commit/0300a2f63efd47bb0223ffb9c79bed18c266c055#diff-be1ffe65777167b25a03edc57337f47e) deals with a project-wide replacement of `long` datatype variables with `int_32t`. 

The latest executable of `CovidSim` built from `master` produces the following error:
> ./src/SetupModel.cpp line 2479: Random number seeds do not match saved values: 98798150 != 98798150 || 0 != 729101

The aforesaid error-checking/printing functionality was introduced in `line 2479` of `src/SetupModel.cpp` in commit [0300a2f63efd47](https://github.com/mrc-ide/covid-sim/commit/0300a2f63efd47bb0223ffb9c79bed18c266c055#diff-be1ffe65777167b25a03edc57337f47e).

By reverting this specific commit in a local testing branch, I can confirm that the error does not occur any more. Can you please look into a fix?

**Comment by ozmorph** [comment]
That commit fixes a cross-platform compatibility issue involving the sizes of an int and a long on Windows vs Linux/OSX. However, it does make sense as to why a network file from an older CovidSim binary would conflict with the newer binary.

It should be possible to run the newer CovidSim binary with the CLI argument `/S:<network_file>` instead of `/L:<network_file>` to regenerate the network file with the new format (you should manually make a backup of `<network_file>` before doing this of course). Then once the simulation is finished, you should be able to use `/L:<network_file>` as normal.

**Comment by weshinsley** [comment]
Exactly right @ozmorph - sizeof(long) is 4 on windows, and 8 on linux, and it seemed helpful for us (and others) to make the network files OS-agnostic. Sorry for the inconvenience - recreating your network file as ozmorph says will do the job. 

(Or if you wanted to perform surgery on an existing network file, you'd need to create a copy that replaces the 8-byte longs stored in bytes 12-19 and 20-27 of the file (zero-indexed) with 4-byte equivalents obtained by casted those longs to int32_t. The rest of the file is the same, but your final network file would be 8 bytes shorter).
