### ISSUE TITLE
Can I generate data for a city level? 

### ISSUE THREAD

**Issue by AmolSakhale** [mrc-ide/covid-sim#457]
Using the present code, I could build the covid model and use integration.py to generate infected cases data for one state. 
Can I run this model only for a particular city or let's say a university population?

**Comment by weshinsley** [comment]
I don't think a single city or university is really what covid-sim is targetted at modelling. It's fundamentally a spatial simulator for modelling policies on different households, schools and workplaces, and people's travel movements (commute/social). I think you would have to switch off quite a lot of things to model a single city or university. You would also probably need higher resolution population data (we are normally using 1/120 degrees lon/lat for state/national/international models), shapefiles for boundaries to separate out places with different policies, and for a university I guess you would be thinking about halls of residence, as some kind of modification of the households covid-sim models.

The parameter files are pretty flexible and I believe it is even possible to turn everything off so that covid-sim behaves like a simple compartmental model, which is probably more the kind of thing you'd need to a single population - perhaps with different compartments for different campuses or halls of residence and mixing equations to establish transmission between them. But generally, I suspect you would get better mileage by starting out with that sort of a mathematical model, rather than trying to whittle covid-sim's parameters down to make it act like one.
