### ISSUE TITLE
Would it be possible to re-introduce tagged releases?

### ISSUE THREAD

**Issue by owainkenwayucl** [mrc-ide/covid-sim#459]
My team maintain a very large suite of packages on our HPC systems centrally installed for users, including multiple versions of CovidSim which we make available to users via modules:

```console
$ module avail covid-19-spatial-sim
------------------ /shared/ucl/apps/modulefiles/applications -------------------
covid-19-spatial-sim/0.8.0/intel-2020  covid-19-spatial-sim/0.14.0/gnu-4.9.2   
covid-19-spatial-sim/0.9.0/gnu-4.9.2   covid-19-spatial-sim/0.14.0/intel-2020  
covid-19-spatial-sim/0.13.0/gnu-4.9.2
```

Unfortunately the last tagged release was v0.14.0 at the end of May and the code base has diverged quite a lot from that version.  I want to install up to date versions but without a tagged release it gets a bit awkward to do that sensibly (the process I tend to take for other packages which don't do releases is to pick a commit on a date and then name that `package/date`).  

Is there a plan to return to making regular tagged releases or should I resort to the commit/date naming scheme?

**Comment by weshinsley** [comment]
Yes, while I don't think there was anything front-facing, or result-changing (deliberately enforced) in changes since 0.14.0, there are a couple of PRs I'm trying to find time to work on to get them merged in which we could tag as a 0.15.0 release... 

We're not at a point where we've got any particular development plan or regular release schedule in mind for the moment for this repo - there are many different projects and priorities across the team as things progress...

**Comment by owainkenwayucl** [comment]
OK - no problem.  

I'll try and come up with a sensible way of naming some development versions.

**Comment by weshinsley** [comment]
So as above, we merged in a bunch of work lingering from Summer, and tagged it as a 0.15.0 release, and we'll try to do that in the future. No changes in actual behaviour or code, essentially removal of warnings, improvements to code style and readability that commenters had menionted, and gradually chipping away and unit-testing different parts. 

But with this codebase, I think it safe to assume running with the most recent version is what most users will want.
